#
# Landing Analysis
#

analysis:

  name: Fixed Wing Landing Analysis

#
# MAVLink messages required
#

messages:

  - BARO
  - GPS
  - ARSP
  - RFND
  - ATT
  - MODE
  - CTUN
  - NTUN
  - XKF1
  - MSG
  - LAND
  - ARM
  - VER

#
# Parameter groups required
#

parameters:

  - LAND_*
  - TECS_*
  - ARSPD_*
  - AHRS_*
  - EK3_*
  - RNGFND*